### ISSUE TITLE
Implementación en Java de Factory Method es incorrecta

### ISSUE THREAD

**Issue by aloussase** [aloussase/patrones-diseno#1]
La implementación actual de Factory Method en Java es incorrecta y va en contra del OCP (Open/Closed Principle): cada vez que se desea añadir una figura se debe modificar la clase `FabricaFigura`. A continuación se muestra el UML de una posible solución:

![image](https://user-images.githubusercontent.com/84427521/124332505-3901f780-db57-11eb-8309-583151877422.png)

La interfaz `IFigura` con sus subclases permanecen, sin embargo `FabricaFigura` se cambió en favor de  `IBackgroundPattern`, que representa un patrón de fondo para una GUI. El método concreto `fillBackground` depende del método abstracto `crearFigura`, de modo que su comportamiento puede ser modificado a través de herencia y no es necesario modificar ninguna clase.

**Comment by anntnzrb** [comment]
Se han efectuado los cambios solicitados, antes de hacer merge a master solicito un revisión. Los cambios se encuentran en el branch [patch-java-factorymethod](https://github.com/aloussase/patrones-diseno/commit/566d971d14dae26401e4a567411d6d4da7dfa469).

**Comment by aloussase** [comment]
Buen trabajo. En `AbstractPatronFondo` tienes estas líneas:

```java
    final void rellenarFondo() {
        final var figura = crearFigura();
        crearFigura().dibujar();
    }
```

Elimina una de las llamadas redundantes al método `crearFigura()`. Por último, mueve todo directamente a `src`, es decir la estructura del proyecto (no actualizado) debería verse algo así:

```
java/
└── src
    ├── factory
    │   ├── FabricaFigura.java
    │   ├── figura
    │   │   ├── Circulo.java
    │   │   ├── Cuadrado.java
    │   │   ├── IFigura.java
    │   │   └── Triangulo.java
    │   └── Main.java
    └── singleton
        ├── Conexion.java
        └── Main.java
``` 

El esquema `src/main/java` solo se utiliza en proyectos de maven o gradle, pero aquí no estamos usando una build tool (puedes convertirlo a un proyecto maven o gradle si prefieres).

Una vez realizados esos cambios le haré merge.

**Comment by anntnzrb** [comment]
> Elimina una de las llamadas redundantes al método `crearFigura()`. Por último, mueve todo directamente a `src` (...)

Hecho; el pequeño detalle con respecto a `crearFigura()` fue adjuntado con el refactor de la estructura del proyecto.

**Comment by aloussase** [comment]
Hice merge a tus cambios. Voy a cerrar el issue
